baseurl: "/branches/develop" # adjust s3 location in Jenkinsfile accordingly

bcurl: https://dev.brightcrowd.com
apibaseurl: https://api.dev.brightcrowd.com

sass:
    style: :expanded

# CORS support during local testing
webrick:
  headers:
    Access-Control-Allow-Origin: '*'
