baseurl: "/branches/develop" # adjust s3 location in Jenkinsfile accordingly

bcurl: http://localhost:9000

sass:
    style: :expanded

# CORS support during local testing
webrick:
  headers:
    Access-Control-Allow-Origin: '*'
