# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BrightCrowd Blog
tagline: 'The Actually Helpful Professional Network'
email: contact@brightcrowd.com
description: >- # this means to ignore newlines until "baseurl:"
  BrightCrowd helps you get stuff done by connecting you to the people in your network with the knowledge and experience you need.
baseurl: "" # adjust s3 location in Jenkinsfile accordingly
url: "https://blog.brightcrowd.com"

bcurl: https://brightcrowd.com

facebook:
  app_id: 1584150891861483
  publisher: https://facebook.com/BrightCrowd

google_analytics: UA-54131651-4

logo: /assets/images/brightcrowd-logo-lg.svg
avatar: /assets/images/brightcrowd-logo-lg.svg
# default image for posts
image: /assets/images/hero3.png

author: tjduane

# Build settings

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-auto-image
  - jekyll-json-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Jenkinsfile
  - CNAME

# config from templates

# Permalinks
permalink: /:title/

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Custom vars
version: 1.1.4


footer-links:
  dribbble:
  email: contact@brightcrowd.com
  facebook: BrightCrowd
  flickr:
  github: BrightCrowd/bc-blog
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: BrightCrowd
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


twitter_username: BrightCrowd
github_username:  BrightCrowd

twitter:
  username: BrightCrowd

github:
  repository_url: https://github.com/Brightcrowd/bc-blog
